library(readr)
library(readxl)
library(readr)
air_data<- read_excel("E:/Assignments/Assignments week 2/m4/EastWestAirlines (2).xlsx",2)
View(air_data)
summary(air_data)
normalize<-scale(air_data[,2:12])
View(normalize)
summary(normalize)
d<- dist(normalize,method='manhattan')
fit<-hclust(d,method="centroid")
plot(fit)
plot(fit,hang=-1)
groups<-cutree(fit,k=3)
rect.hclust(fit,k=3,border='red')
customers<-as.matrix(groups)
final_segmentation<-data.frame(customers,air_data)
View(air_data)
View(final_segmentation)
aggregate(air_data[,2:5],by=list(final_segmentation$customers),FUN = mean)
library(readr)
write_csv(final_segmentation,"customersegmentationcent.csv")
getwd()
