library(readr)
 library(readxl)
 library(readr)
 crime_data <- read_csv("E:/Assignments/Assignments week 2/m4/crime_data.csv")
View(crime_data)
 summary(crime_data)
 normalize<-scale(crime_data[,2:5])
 View(normalize)
summary(normalize)
 d<- dist(normalize,method='euclidean')
 fit<-hclust(),method="single"
fit<-hclust(d,method="complete")
 plot(fit)
 plot(fit,hang=-1)
 groups<-cutree(fit,k=2)
 rect.hclust(fit,k=2,border='red')
 crimes<-as.matrix(groups)
 final<-data.frame(crimes,crime_data)
 View(crime_data)
 View(final)
 aggregate(crime_data[,2:5],by=list(final$crimes),FUN = mean)
 library(readr)
 write_csv(final,"crimess.csv")
 getwd()

